### ISSUE TITLE
some graphical glitches with the recently changed strikedown and trinity

### ISSUE THREAD

**Issue by USMP-lancer** [MEEPofFaith/prog-mats-java#1]
![image](https://user-images.githubusercontent.com/42185819/130159010-256f3b35-6d61-49c7-9a11-f265fc8a45b5.png)
![image](https://user-images.githubusercontent.com/42185819/130159041-8ce0e656-6664-47b8-9061-4832ed8a18a6.png)

**Comment by USMP-lancer** [comment]
also rip droppod im guessing?

**Comment by MEEPofFaith** [comment]
aaaa

**Comment by USMP-lancer** [comment]
mood

**Comment by USMP-lancer** [comment]
the strikedown graphic bug also shows ingame, when a conveyor is attached. it looks like it shows all overlays in build thing

**Comment by MEEPofFaith** [comment]
~~yea deleting the size 4 payload input was a mistake, forgot that Strikedown is a 4x4~~

**Comment by USMP-lancer** [comment]
~~lmao~~
