### ISSUE TITLE
rocket layer bug

### ISSUE THREAD

**Issue by uujuju1** [MEEPofFaith/prog-mats-java#11]
**Platform**: *Windows*

**Build**: *134*

**Mod Version**: *v17.3 or commit test #171*

**Issue**: *everytime arbalest shoots into the dark the missile is covered*

**Steps to reproduce**: *place arbalest, load arbalest with any ammo, shoot to the darkness*

**Save file**: *it happens at any save with a dark part*

**Last log**: *none*

**Crash logs**: *none*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
  - [ ] **I am playing with the latest release (https://github.com/MEEPofFaith/prog-mats-java/releases) to make sure my issue has not been fixed.**
   
    or
  - [X] **I am playing with the latest action (https://github.com/MEEPofFaith/prog-mats-java/actions) to make sure my issue has not been fixed.**

---

The original template is by Anuke, modified by sk7725, modified by MEEPofFaith.

**Comment by MEEPofFaith** [comment]
seems fine to me

https://user-images.githubusercontent.com/54301439/139592859-1ea58440-9b9b-4675-a303-7d6cc8b05d10.mp4

**Comment by MEEPofFaith** [comment]
If you're talking about how it goes under the shadow then either I have the missile clip through the small covering when it fires or I remove the small covering.

![image](https://user-images.githubusercontent.com/54301439/139592969-9a5bd3be-6a7e-4ba7-92b8-1500966757a4.png)

**Comment by uujuju1** [comment]
i was saying about the dark spots in the map
thee missile doesnt have any light that is why it goes under the shadow iguess

**Comment by uujuju1** [comment]
![mod](https://user-images.githubusercontent.com/84468589/139599767-d594bcfc-7b08-4ece-8bcf-60dbda6bf002.PNG)

**Comment by MEEPofFaith** [comment]
oh that's just the layer, light has nothing to do with the dark areas in the map
