### ISSUE TITLE
This isn't a bug

### ISSUE THREAD

**Issue by vghfr** [MEEPofFaith/prog-mats-java#14]
meep help
Do you have any idea how to change a block's texture based on it's state?

**Comment by MrDuck557** [comment]
If you're actually making a java mod, override draw
Use if statements to choose which texture to draw

**Comment by vghfr** [comment]
It's not a java mod. Also, please elaborate

**Comment by MrDuck557** [comment]
> It's not a java mod.

why are you asking
in the issues of a java mod
is it javascript mod?

> Also, please elaborate

if it's not a java mod, do I need to?

**Comment by vghfr** [comment]
> is it javascript mod?

Yes.
> why are you asking
in the issues of a java mod

Honestly, I wanted to ask somewhere and saw this in my feed so I tried this

**Comment by MrDuck557** [comment]
do you know that the mindustry discord has a #modding-general channel

**Comment by vghfr** [comment]
> do you know that the mindustry discord has a #modding-general channel

Yes. I'll ask there.
