### ISSUE TITLE
Доделать здания.

### ISSUE THREAD

**Issue by Creater3d** [MEEPofFaith/prog-mats-java#15]
Platform: Windows.

Build: 135.

Mod Version: 23,3.
Issue: Сборщик ракет - не работает, нужно починить, а так же капсула в платформе для дронов не стикает полностью, при подключений труб через раз застой и ни обновляется капсула, чтоб ещё раз привезти.

**Comment by MEEPofFaith** [comment]
Sorry, I can't understand Russian.

**Comment by AzhurniyBaklan** [comment]
@Creater3d 
Переводчик от мод-комьюнити на связи!
Прошу предоставить больше информации по сборщику ракет, разработчик не совсем понимает, в чём может быть проблема.
По поводу труб - это лишь недоработка самой системы, и может быть будет пофикшено в дальнейшем. А может и нет. Оставайтесь на связи!
UPD: Ваше мнение было услышано, хотфикс по жидкостям уже в пути. По первому пункту пока ничего не ясно.

**Comment by Creater3d** [comment]
> Sorry, I can't understand Russian.

Discord - Creater3d #3915.

**Comment by Creater3d** [comment]
> @Creater3d Переводчик от мод-комьюнити на связи! Прошу предоставить больше информации по сборщику ракет, разработчик не совсем понимает, в чём может быть проблема. По поводу труб - это лишь недоработка самой системы, и может быть будет пофикшено в дальнейшем. А может и нет. Оставайтесь на связи! UPD: Ваше мнение было услышано, хотфикс по жидкостям уже в пути. По первому пункту пока ничего не ясно.

Ты есть на дискорде?

**Comment by Creater3d** [comment]
![2](https://user-images.githubusercontent.com/73776761/151176936-93c4b8af-9aac-4d86-a086-9e16e5df833e.png)
Ни строются ракеты, стоит прогрээс строительства на нуле и ни наполняется жыдкостью сборщик ракет. (граматика правильная, а ни ложная которую учат в школе), нужно доделать или может они по другому строятся?

**Comment by MEEPofFaith** [comment]
Check the block's stats.
The missiles need a shell to be built.

**Comment by MEEPofFaith** [comment]
Тебе нужно сначала построить корпус ракеты, иначе не работает

![image](https://user-images.githubusercontent.com/54301439/151304107-f8f0b87f-e2d9-4e3b-914b-895f3408654f.png)
