### ISSUE TITLE
Opening info screen on Death Factory (sandbox only, probably) crashes the game

### ISSUE THREAD

**Issue by TheGamer1002** [MEEPofFaith/prog-mats-java#16]
**Platform**: *Windows*

**Build**: *Pre-alpha 135 + Foo's Client v913*

**Mod Version**: *v23.6*

**Issue**: *Viewing details of the Death Factory block crashes the game. [java.lang.RuntimeException: No stat entry found: "itemCapacity" in block.]*
**Steps to reproduce**: 

1. Open game
2. Go to mod menu
3. Click on Progressed Materials (Java)
4. Click View Content
5. Click Death Factory
6. Profit

```java
Version: pre-alpha build 135
(Client Version: 913, Feb. 10, 2022 Unstable)
Source: mindustry-antigrief/mindustry-client-v7-builds
OS: Windows 11 x64 (amd64)
Java Version: 17.0.2
Mods: 2xconveyors:0.2, aeromindustry:1, anuke-logic:1.9.6, basic-schematics:1, betamindy:1.08, cliff:1.1.0, dev-mode:2.3.2, distributor:1.0.1, esoterum:2.11-119, exogenesis:[blue]1.4, inverted-machines:1.4, mainstreamdustry:dustry, mind-util:1.3.0, modding-toolbox:3.7.4, more-defences-ivyx:1.0, multi-lib:1.0.7, new-horizon:1.10.9.1, newconsole:1.41, opore-mod:69, pictologic:1.5.7, prog-mats:23.6, purple-air:0.2.2, radar:2.10.5, revision:12.5, routorio:2.36.3, rtfm:2.15.0, sandboxmode:1, schematics-pack:8, scheme-size:2.2.20, shar:0.2v, shitshow:0.1, speed:2.2.1, test-mod:0.98 Beta, time-control:0.2, tracker:2.5.2, uaw:0.7.7, ui-lib:2.16.6, unit-factory:2.5.0, unitinfo:1.5.3, units-mod:1.0, unnerf_core_units:1.1, waisa:2.3.3

java.lang.RuntimeException: No stat entry found: "itemCapacity" in block.
	at mindustry.world.meta.Stats.remove(Stats.java:95)
	at mindustry.world.blocks.units.UnitFactory.setStats(UnitFactory.java:104)
	at mindustry.ctype.UnlockableContent.checkStats(UnlockableContent.java:80)
	at mindustry.ui.dialogs.ContentInfoDialog.show(ContentInfoDialog.java:30)
	at mindustry.ui.dialogs.ModsDialog.lambda$showMod$48(ModsDialog.java:402)
	at arc.scene.Element.lambda$clicked$2(Element.java:893)
	at arc.scene.Element$4.clicked(Element.java:902)
	at arc.scene.event.ClickListener.touchUp(ClickListener.java:77)
	at arc.scene.event.InputListener.handle(InputListener.java:31)
	at arc.scene.Scene.touchUp(Scene.java:366)
	at arc.input.InputMultiplexer.touchUp(InputMultiplexer.java:136)
	at arc.input.InputEventQueue.drain(InputEventQueue.java:71)
	at arc.backend.sdl.SdlInput.update(SdlInput.java:100)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:151)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:45)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:74)
```
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
  - [x] **I am playing with the latest release (https://github.com/MEEPofFaith/prog-mats-java/releases) to make sure my issue has not been fixed.**
   
---

The original template is by Anuke, modified by sk7725, modified by MEEPofFaith.

**Comment by MEEPofFaith** [comment]
> Profit

lmao

anyways off to try to recreate this issue and fix it

(Wow for once an actually helpful bug report. Been a while since I've seen one.)

**Comment by MEEPofFaith** [comment]
I believe it might be an issue with Foo's, try not using Foo's and see if you still have the issue. I'm not getting the same crash.

The stacktrace in the crash report is also not showing anything that leads to my block.

**Comment by TheGamer1002** [comment]
Hmm, yep, might be Foo's. Been getting a few hangs lately too. I might try getting a fresh Foo's install.

**Comment by TheGamer1002** [comment]
Yeah, interesting, even with a fresh Foo's it crashes. Over to their issue section!

**Comment by buthed010203** [comment]
~~I can't reproduce this with the client... I don't know what you're doing to make it happen but it doesn't happen to me so idk.
Perhaps its one of the other 300 mods you have enabled or something, I have no clue honestly~~

Edit: I lied, never read the bug report and got the crash when actually looking at the stats lol

Edit2: Tracked it down finally... Looks like somehow I managed to fuck up a merge about a year ago (makes sense as I had like 0 experience with git at that point)... Ended up still having the code from this ancient commit: https://github.com/Anuken/Mindustry/commit/ec19381c4e9afc92c4d5c1ef5ed3d9769cf3d231#diff-b2da0a661cc2a4580544ec8d4184b09e41cdaef7acc4653e55733115a9fdde56
