### ISSUE TITLE
arc.util.ArcRuntimeException: File not found: shaders/default.vert (internal)

### ISSUE THREAD

**Issue by MaxSMokeSkaarj** [MEEPofFaith/prog-mats-java#17]
**Platform**: *Linux*

**Build**: *135 server*

**Mod Version**: *latest(23.6)*

**Issue**: *arc.util.ArcRuntimeException: File not found: shaders/default.vert (internal), photo includes, UPD same error on latest action & release mods*

**Steps to reproduce**: *just add latest mod on mods dir and run server*

**Save file**: *-*

**Last log**: *includes*

**Crash logs**: *server havent a crash log btw*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
  - [X] **I am playing with the latest release (https://github.com/MEEPofFaith/prog-mats-java/releases) to make sure my issue has not been fixed.**
   
    or
  - [X] **I am playing with the latest action (https://github.com/MEEPofFaith/prog-mats-java/actions) to make sure my issue has not been fixed.**

---

The original template is by Anuke, modified by sk7725, modified by MEEPofFaith.

files:
![Снимок экрана_2022-02-28_08-43-21](https://user-images.githubusercontent.com/62266921/155903141-9e3d6332-6447-4727-8901-c21ba9898152.png)
[log-0.txt](https://github.com/MEEPofFaith/prog-mats-java/files/8149550/log-0.txt)

**Comment by MEEPofFaith** [comment]
time to see how Mindustry loads shaders to fix this

**Comment by MEEPofFaith** [comment]
Try downloading the mod from the [commit's workflow artifacts](https://github.com/MEEPofFaith/prog-mats-java/actions/runs/1917788195) and see if the issue persists.

**Comment by MEEPofFaith** [comment]
I tried it myself, and it is fixed. Cool.
