### ISSUE TITLE
Sentry can be placed in non-sandbox

### ISSUE THREAD

**Issue by Auseawesome** [MEEPofFaith/prog-mats-java#18]
**Platform**: Windows

**Build**: build 135

**Mod Version**: v23.6

**Issue**: Sentry can be placed when not in sandbox by grabbing off payload conveyor with a mega or similar unit and placed down

**Steps to reproduce**: Get a sentry factory to make any sentry and output to payload conveyor. Fly over conveyor with mega or other unit and press the pick up payload key then you have successfully obtained the sentry block in non-sandcox

**Save file**: Not needed

**Last log**: Not Needed

**Crash logs**: Not Needed

- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
  - [X] **I am playing with the latest release (https://github.com/MEEPofFaith/prog-mats-java/releases) to make sure my issue has not been fixed.**

**Comment by MEEPofFaith** [comment]
What did you expect, all the payloads are blocks. Of course you're gonna be able to pick them up off of a payload conveyor and drop them on the floor.

**Comment by MEEPofFaith** [comment]
They even have special functionally as blocks, missiles violent explode if shot and destroyed, and you can manually activate sentries by clicking on them.
