### ISSUE TITLE
conveyor input overlay displays in item menu

### ISSUE THREAD

**Issue by USMP-lancer** [MEEPofFaith/prog-mats-java#2]
just a mineor issue, consider this low priority

**Comment by MEEPofFaith** [comment]
?

send screnshot

**Comment by USMP-lancer** [comment]
![image](https://user-images.githubusercontent.com/42185819/130170186-42f8f9bb-7b10-49cc-abc6-ee4d81fa0c1e.png)

**Comment by USMP-lancer** [comment]
rather strange, but makes a little sense imo

**Comment by USMP-lancer** [comment]
i can only assume striker would render the same, but current release has the ohno atm so

**Comment by USMP-lancer** [comment]
also random question where did drop pod go?

**Comment by MEEPofFaith** [comment]
I couldn't figure out how it would be crafted since you can only have 1 payload inside of a building at once so I just deleted it.

**Comment by USMP-lancer** [comment]
rip, well what will fill its void i wonder, OOH, lingering nuke perhaps, just a lingering aoe thing probably, taking a bit of phase because yes

**Comment by MEEPofFaith** [comment]
Added back in missing sprite, no more ohno in the menu.
