### ISSUE TITLE
ur mod makes game die pls fix

### ISSUE THREAD

**Issue by LibreBulb** [MEEPofFaith/prog-mats-java#22]
**Platform**: *Windows*

**Build**: *22562*

**Mod Version**: *the game literally dies when I try to launch with the mod on so not possible*

**Issue**: *When launching the latest BE, game dies. Singled out the crash cause to this mod.*

**Steps to reproduce**: *literally double click on the jar/extension with the mod on*

**Save file**: *The (zipped) save file you were playing on when the bug happened. Not required, but you will be asked for it in certain bugs.*

**Last log**: *
[last_log.txt](https://github.com/MEEPofFaith/prog-mats-java/files/8887986/last_log.txt)
 Hackdustry and the other v6 mod are for testing purposes i dont even play multiplayer*

**Crash logs**: *
[crash-report-06_12_2022_22_46_46.txt](https://github.com/MEEPofFaith/prog-mats-java/files/8887969/crash-report-06_12_2022_22_46_46.txt)
*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
  - [X] **I am playing with the latest release (https://github.com/MEEPofFaith/prog-mats-java/releases) to make sure my issue has not been fixed.**

---

The original template is by Anuke, modified by sk7725, modified by MEEPofFaith.

**Comment by LibreBulb** [comment]
nope still crashes game (Even when downloading straight from github)

**Comment by MEEPofFaith** [comment]
I can't reproduce this.
Even if you can't check what version of PM you're using from the mod menu, you should at least be able to figure out what you're downloading.

**Comment by MEEPofFaith** [comment]
It seems like you have an outdated version of BE.
I'm on 22639 and it's fine.
