### ISSUE TITLE
Вылет игры при постройке сборщика ракет. /google translate -->/Crash when building a rocket assembler.

### ISSUE THREAD

**Issue by TheNickname99** [MEEPofFaith/prog-mats-java#23]
(sorry for bad english if it's bad)

**Platform**: *Android//Windows/Linux*
Android
**Build**: *The build number under the title in the main menu. Required.*
22768 or 136
**Mod Version**: *Mod version in menus. If you download from actions, which action did you download from.*
pre-erekir
**Issue**: *Explain your issue in detail.*
game crashes when i build rocket assembler. /google translate because i'm lazy -->/When viewing the data (clicking on the question mark), previewing the construction or building "under-finished" in survival, but when the construction is completed, the game crashes.//
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
^^^
**Save file**: *The (zipped) save file you were playing on when the bug happened. Not required, but you will be asked for it in certain bugs.*
no save file. 
**Last log**: *The `last_log.txt` from your game folder (.../Mindustry). REQUIRED if a certain block is not working at ALL, usually the case in headless servers.*

———last log———

[I] [GL] Version: GLES 3.2.0 / Qualcomm / Adreno (TM) 506
[I] [GL] Max texture size: 16384
[I] [GL] Using OpenGL 2 context.
[I] [JAVA] Version: 0
[I] [RAM] Available: 256.0 MB
[I] Loaded mod 'miner-tools' in 37.029427ms
[I] Loaded mod 'oblivion' in 230.54745ms
[I] Loaded mod 'prog-mats' in 409.9199ms
[I] Loaded mod 'ammo-swap' in 1.470885ms
[I] Loaded mod 'test-utils' in 23.23224ms
[I] [AndroidGraphics] [pause]
[I] [AndroidGraphics] [resume]
[I] Total time to load: 46080ms
[I] Fetching community servers at https://raw.githubusercontent.com/Anuken/Mindustry/master/servers_be.json
[I] MinerToolsSettings: Trying to load settings
[I] MinerToolsSettings: Load settings successfully
[I] changed
[I] Fetched 7 community servers.
[I] [AndroidGraphics] [pause]
[I] [AndroidGraphics] [resume]
[I] [AndroidGraphics] [pause]
[I] [AndroidGraphics] [resume]
[I] [AndroidGraphics] [pause]

———end———

**Are you love routers?**:*Are you love routers?*
yes
**Crash logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

———crash log———

Mindustry has crashed. How unfortunate.
Version: bleeding-edge build 22678
OS: Linux xnull (armv8l)
Android API level: 29
Java Version: 0
Runtime Available Memory: 256mb
Cores: 8
Mods: miner-tools:1.6.5, prog-mats:25.1, test-utils:41

> NullPointer: 'Attempt to read from field 'mindustry.type.Liquid mindustry.type.LiquidStack.liquid' on a null object reference'
ConsumeLiquidDynamic.efficiency: 61
PowerGraph.otherConsumersAreValid: 2
PowerGraph.getPowerNeeded: 5
PowerGraph.update: 5
PowerGraphUpdater.update: 2
EntityGroup.update: 2
Groups.update: 5
Logic.update: 38
ApplicationCore.update: 2
ClientLauncher.update: 17
AndroidGraphics.onDrawFrame: 22
GLSurfaceView$GLThread.guardedRun: 1573
GLSurfaceView$GLThread.run: 1272

———end———

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
  - [X] **I am playing with the latest release (https://github.com/MEEPofFaith/prog-mats-java/releases) to make sure my issue has not been fixed.**
   
    or
  - [ ] **I am playing with the latest action (https://github.com/MEEPofFaith/prog-mats-java/actions) to make sure my issue has not been fixed.**

---

The original template is by Anuke, modified by sk7725, modified by MEEPofFaith.

**Comment by MEEPofFaith** [comment]
You have an outdated version.
