### ISSUE TITLE
Вылет игры при "нажатии" на турель "apotheosis Nexus". /google translate--->/The game crashed when "clicking" on the "apotheosis Nexus" turret.

### ISSUE THREAD

**Issue by TheNickname99** [MEEPofFaith/prog-mats-java#24]
sorry for bad english

**Platform**: *Android//Windows/Linux*
Android
**Build**: *The build number under the title in the main menu. Required.*
22768, or 136 (pre-erekir)
**Mod Version**: *Mod version in menus. If you download from actions, which action did you download from.*
pre-erekir, action: bug fix #23 
**Issue**: *Explain your issue in detail.*
/google translate--->/When you click (view information) on the "apotheosis Nexus" turret, the game crashes.  There is a view of information as CURRENT health.
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
i clicked on turret "apotheosis Nexus". Maybe on PC i must choose this turret by cursor. Sorry, if my english is bad.
**Save file**: *The (zipped) save file you were playing on when the bug happened. Not required, but you will be asked for it in certain bugs.*
no save file
**Last log**: *The `last_log.txt` from your game folder (.../Mindustry). REQUIRED if a certain block is not working at ALL, usually the case in headless servers.*

[I] [GL] Version: GLES 3.2.0 / Qualcomm / Adreno (TM) 506
[I] [GL] Max texture size: 16384
[I] [GL] Using OpenGL 2 context.
[I] [JAVA] Version: 0
[I] [RAM] Available: 256.0 MB
[I] Loaded mod 'informatis' in 51.09302ms
[I] Loaded mod 'miner-tools' in 36.69229ms
[I] Loaded mod 'oblivion' in 225.69751ms
[I] Loaded mod 'prog-mats' in 315.79153ms
[I] Loaded mod 'ammo-swap' in 1.406667ms
[I] Loaded mod 'test-utils' in 21.375883ms
[I] Loaded mod 'betamindy' in 686.39355ms
[I] Total time to load: 31529ms
[I] Fetching community servers at https://raw.githubusercontent.com/Anuken/Mindustry/master/servers_be.json
[I] MinerToolsSettings: Trying to load settings
[I] MinerToolsSettings: Load settings successfully
[I] changed
[I] Fetched 7 community servers.
[I] [AndroidGraphics] [pause]
[I] [AndroidGraphics] [resume]
[I] [AndroidGraphics] [pause]

**Crash logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

[I] [GL] Version: GLES 3.2.0 / Qualcomm / Adreno (TM) 506
[I] [GL] Max texture size: 16384
[I] [GL] Using OpenGL 2 context.
[I] [JAVA] Version: 0
[I] [RAM] Available: 256.0 MB
[I] Loaded mod 'informatis' in 51.09302ms
[I] Loaded mod 'miner-tools' in 36.69229ms
[I] Loaded mod 'oblivion' in 225.69751ms
[I] Loaded mod 'prog-mats' in 315.79153ms
[I] Loaded mod 'ammo-swap' in 1.406667ms
[I] Loaded mod 'test-utils' in 21.375883ms
[I] Loaded mod 'betamindy' in 686.39355ms
[I] Total time to load: 31529ms
[I] Fetching community servers at https://raw.githubusercontent.com/Anuken/Mindustry/master/servers_be.json
[I] MinerToolsSettings: Trying to load settings
[I] MinerToolsSettings: Load settings successfully
[I] changed
[I] Fetched 7 community servers.
[I] [AndroidGraphics] [pause]
[I] [AndroidGraphics] [resume]
[I] [AndroidGraphics] [pause]

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
  - [ ] **I am playing with the latest release (https://github.com/MEEPofFaith/prog-mats-java/releases) to make sure my issue has not been fixed.**
   
    or
  - [X] **I am playing with the latest action (https://github.com/MEEPofFaith/prog-mats-java/actions) to make sure my issue has not been fixed.**

---

The original template is by Anuke, modified by sk7725, modified by MEEPofFaith.

**Comment by MEEPofFaith** [comment]
I believe you accidntally posted last_log instead of a crash report.

**Comment by TheNickname99** [comment]
i'm sorry. here's a crash report :

———

Mindustry has crashed. How unfortunate.
Version: bleeding-edge build 22678
OS: Linux xnull (armv8l)
Android API level: 29
Java Version: 0
Runtime Available Memory: 256mb
Cores: 8
Mods: informatis:1.6, miner-tools:1.6.5, prog-mats:26, test-utils:41

> ClassCast: 'progressed.content.blocks.PMBlocks$29 cannot be cast to
mindustry.world.blocks.defense.turrets.Turret'
BarInfo.getInfo: 80
Main.lambda$init$1: 29
-$$Lambda$Main$vg9JC4cfZuHUD7SB37CHpYl8ar0.run: 0
Events.lambda$run$2: 0
Events.$r8$lambda$r1ZaaGUtG03In-r__kf9lAmJrDc: 0
Events$$ExternalSyntheticLambda0.get: 32
Events.fire: 4
Logic.update: 1
ApplicationCore.update: 2
ClientLauncher.update: 17
AndroidGraphics.onDrawFrame: 22
GLSurfaceView$GLThread.guardedRun: 1573
GLSurfaceView$GLThread.run: 1272

———

ср, 22 июн. 2022 г., 09:39 MEEPofFaith ***@***.***>:

**Comment by TheNickname99** [comment]
/google translate/ Should I re-report the problem or will it come out of the commentary?

**Comment by MEEPofFaith** [comment]
it's fine

**Comment by TheNickname99** [comment]
When will be fixed version? This issue marked as completed, but last action still "fix #23"

**Comment by MEEPofFaith** [comment]
I figured out this issue is because of informatis.
