### ISSUE TITLE
Странные текстуры повреждения / wierd damage textures (mini issue)

### ISSUE THREAD

**Issue by TheNickname99** [MEEPofFaith/prog-mats-java#27]
action #478, Android.

![Screenshot_20220711-193043_Mindustry BE](https://user-images.githubusercontent.com/107668259/178411522-4ec614b8-892f-4661-9079-a793ac498f92.jpg)
pantheon don't have any damage textures, and another turret have it wierd.
another mods: testing utilities only

**Comment by MEEPofFaith** [comment]
The game doesn't have damage textures for blocks that big.

https://user-images.githubusercontent.com/54301439/178571682-d9d51921-8bc9-4285-8a22-b1390c9213d6.mp4

**Comment by TheNickname99** [comment]
oh... ok
