### ISSUE TITLE
Текстуры... опять... (mini issue)

### ISSUE THREAD

**Issue by TheNickname99** [MEEPofFaith/prog-mats-java#28]
![Screenshot_20220713-115057_Mindustry BE](https://user-images.githubusercontent.com/107668259/178831632-a4beb57c-54ea-49df-a8fd-8ad630203c2f.jpg)
Phone of bullets are empty, but not cleared.

![Screenshot_20220711-192653_Mindustry BE](https://user-images.githubusercontent.com/107668259/178831925-5120a5ab-c431-4d0a-8103-76bde030859b.jpg)
normal texture for example...

![Screenshot_20220711-192705_Mindustry BE](https://user-images.githubusercontent.com/107668259/178831962-fb2d277c-49bc-4b49-ae64-14f806424e74.jpg)
...and target under flying units.

sorry, if any issue already posted.

**Comment by MEEPofFaith** [comment]
Some air units are drawn above the "bloom" layer.
![image](https://user-images.githubusercontent.com/54301439/178850796-6929a57f-a1cd-4c2d-86b3-a1aa73360817.png)
