### ISSUE TITLE
Crash on Startup in BE Build 22901 and Alpha Build 137

### ISSUE THREAD

**Issue by DreadEthos616** [MEEPofFaith/prog-mats-java#29]
**Platform**: *Android*

**Build**: *BE Build 22901 & Alpha Build 137*

**Mod Version**: *26.2*

**Issue**: *The game crashes on startup when the mod is enabled.*

**Steps to reproduce**: *Open Mindustry when the mod is enabled.*

**Last log**: 
*BE Build 22901: 
[last_log.txt](https://github.com/MEEPofFaith/prog-mats-java/files/9213245/last_log.txt)*

*Alpha Build 137: 
[last_log.txt](https://github.com/MEEPofFaith/prog-mats-java/files/9262266/last_log.txt)*

**Crash logs**: 
*BE Build 22901: [crash_1659032209618.txt](https://github.com/MEEPofFaith/prog-mats-java/files/9213247/crash_1659032209618.txt)*

*Alpha Build 137: 
[crash_1659637233139.txt](https://github.com/MEEPofFaith/prog-mats-java/files/9262276/crash_1659637233139.txt)*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
  - [X] **I am playing with the latest release (https://github.com/MEEPofFaith/prog-mats-java/releases) to make sure my issue has not been fixed.**
   
    or
  - [X] **I am playing with the latest action (https://github.com/MEEPofFaith/prog-mats-java/actions) to make sure my issue has not been fixed.**

---

The original template is by Anuke, modified by sk7725, modified by MEEPofFaith.

**Comment by eris-webserv** [comment]
Does the mod work on 136.1?

**Comment by DreadEthos616** [comment]
> Does the mod work on 136.1?

Yes. {And it was working on the Bleeding Edge version until I updated it to build 22901.}

**Comment by Austin5003** [comment]
Deprecation go brrrr

**Comment by eris-webserv** [comment]
Don't use BE then

**Comment by TheNickname99** [comment]
I have this problem too

**Comment by MEEPofFaith** [comment]
Imagine using BE

**Comment by TheNickname99** [comment]
But... problem still not fixed...  


Please.. I can't life without this mod  :(

**Comment by DreadEthos616** [comment]
Deprecation Moment 😔

{Transferred my save data to Build 136.1, lul.}

**Comment by eris-webserv** [comment]
> But... problem still not fixed...
> 
> Please.. I can't life without this mod :(

Use. Build. 136. It's literally JUST a v7 beta build.

**Comment by DreadEthos616** [comment]
> Imagine using BE

The crash is now happening in the latest Alpha as well, LMAO. 
(Which as of a few minutes ago is no longer 136.1)

**Comment by eris-webserv** [comment]
@DreadEthos616 He already fixed it.

**Comment by DreadEthos616** [comment]
> @DreadEthos616 He already fixed it.

I know. 👍 {I updated this issue before PROG-MATS updated to 26.3}
