### ISSUE TITLE
how does one man configure a configurable mender

### ISSUE THREAD

**Issue by TheEt1234** [MEEPofFaith/prog-mats-java#32]
enter doesn't do anything 

shooting just sets it to default and closes the tab

i am out of ideas

**Comment by MEEPofFaith** [comment]
Have you considered typing into the text boxes?

https://user-images.githubusercontent.com/54301439/197244117-273f1ece-ea30-454d-b1e3-26cafb9e09bd.mp4

**Comment by SMOLKEYS** [comment]
lmao
