### ISSUE TITLE
Crash on startup Beta 140

### ISSUE THREAD

**Issue by NeUver3n** [MEEPofFaith/prog-mats-java#33]
**Platform**: *Windows*

**Build**: *Beta Build 140*

**Mod Version**: *26.4*

**Issue**: *The game crashes on startup when the mod is enabled*

**Steps to reproduce**: *Above*

**Last log**: *[last_log.txt](https://github.com/MEEPofFaith/prog-mats-java/files/9908649/last_log.txt)*

**Crash logs**: *[crash-report-11_01_2022_12_33_36.txt](https://github.com/MEEPofFaith/prog-mats-java/files/9908651/crash-report-11_01_2022_12_33_36.txt)*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
  - [X] **I am playing with the latest release (https://github.com/MEEPofFaith/prog-mats-java/releases) to make sure my issue has not been fixed.**
   
    or
  - [X] **I am playing with the latest action (https://github.com/MEEPofFaith/prog-mats-java/actions) to make sure my issue has not been fixed.**

---

The original template is by Anuke, modified by sk7725, modified by MEEPofFaith.

**Comment by littlekatter330** [comment]
@MEEPofFaith PLEASE FIX THIS NOW

**Comment by MEEPofFaith** [comment]
god damnit I'm already dealing with the next major update currently half-done and stuck in limbo
