### ISSUE TITLE
I have no idea what this website is, I just wanted to ask why module no work.

### ISSUE THREAD

**Issue by WhimsicalLittleDawg** [MEEPofFaith/prog-mats-java#35]
Stuff like council or something don't do anything

**Comment by Austin5003** [comment]
Did you put the thing in the thing?

**Comment by MEEPofFaith** [comment]
Did you the the

**Comment by WhimsicalLittleDawg** [comment]
I've tried putting the transparent turrets on it, but it wouldn't let me

**Comment by MEEPofFaith** [comment]
You kinda just

https://user-images.githubusercontent.com/54301439/211899452-7a3a6b3a-78cb-4b91-962f-70039a3c8790.mp4

**Comment by WhimsicalLittleDawg** [comment]
Thank you! This was so frustrating beyond anything I've ever dealt with. So that's what that hunk of metal was for.

**Comment by MEEPofFaith** [comment]
poor descriptions moment
