### ISSUE TITLE
Crash issue low priority

### ISSUE THREAD

**Issue by Otamamori917** [MEEPofFaith/prog-mats-java#38]
**Platform**: *Android*

**Build**: *142*

**Mod Version**: *Prog-matts(v27.2aaaaaaaaaaaaaaaaaaaaa),Animalia(v1.0.2-java).*

**Issue**: *More of a mod compatibility issue but upon spawning flarogus game crashes*

**Steps to reproduce**: *just spawn flarogus with both mods activated.*

**Crash logs**: 
*Mindustry has crashed. How unfortunate.
Version: release build 142
OS: Linux xnull (aarch64)
Android API level: 31
Java Version: 0
Runtime Available Memory: 192mb
Cores: 8
Mods: animalia:java 1.0, prog-mats:27.2*

> ClassCast: 'mindustry.gen.UnitEntity cannot be cast to animalia.entities.units.FrogEntity'
FrogWeapon.draw: 22
UnitType.drawWeapons: 3
UnitType.draw: 35
PMUnitTypes$8.draw: 246
UnitEntity.draw: 18
Logic$$ExternalSyntheticLambda0.get: 9
EntityGroup.draw: 6
Renderer.draw: 44
Renderer.update: 43
ApplicationCore.update: 2
ClientLauncher.update: 17
AndroidGraphics.onDrawFrame: 22
GLSurfaceView$GLThread.guardedRun: 1593
GLSurfaceView$GLThread.run: 1287

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
  - [x] **I am playing with the latest release (https://github.com/MEEPofFaith/prog-mats-java/releases) to make sure my issue has not been fixed.**
    or
  - [x] **I am playing with the latest action (https://github.com/MEEPofFaith/prog-mats-java/actions) to make sure my issue has not been fixed.**

---

The original template is by Anuke, modified by sk7725, modified by MEEPofFaith.

**Comment by MEEPofFaith** [comment]
flarogus is not a frog, so ¯\\_(ツ)_/¯

~~Hey @FlinTyX.~~
