### ISSUE TITLE
Turrets sergeant, arbalest, paragon, and artemis break in version 144.2

### ISSUE THREAD

**Issue by Otamamori917** [MEEPofFaith/prog-mats-java#39]
![Screenshot_20230522_155418_Mindustry](https://github.com/MEEPofFaith/prog-mats-java/assets/117782096/d50f5591-d3d0-431a-a16e-9b47c49559f0)
![Screenshot_20230522_160529_Mindustry](https://github.com/MEEPofFaith/prog-mats-java/assets/117782096/762f40ca-da90-41b5-88a8-b37ae1a2b7b5)
![Screenshot_20230522_160600_Mindustry](https://github.com/MEEPofFaith/prog-mats-java/assets/117782096/53d8c5c2-0593-4e3a-85b1-9370d5d26cdb)
![Screenshot_20230522_160542_Mindustry](https://github.com/MEEPofFaith/prog-mats-java/assets/117782096/44935f02-ab86-4168-995c-5e9ab18f0a6e)
![Screenshot_20230522_160535_Mindustry](https://github.com/MEEPofFaith/prog-mats-java/assets/117782096/9bda7ca3-db61-4a92-a785-bcbb602abdb1)

**Comment by MEEPofFaith** [comment]
https://github.com/Anuken/Mindustry/commit/871548c095a46c23e54a8d648abefba183261427
