### ISSUE TITLE
This mod has a problem with working on servers

### ISSUE THREAD

**Issue by other-erisfg** [MEEPofFaith/prog-mats-java#41]
**Platform**: *Linux (ARM64, Oracle Cloud, Ubuntu 22.04)*

**Build**: *145.1*

**Mod Version**: *Latest (Downloaded from Github page, mod checked to be the newest version prior to report)*

**Issue**: *Putting the mod on a server and starting said server will crash the server with a bunch of null-pointer errors.*

**Steps to reproduce**: *Install Progression Ministry to a server.*

**Save file**: *This happened while the server was still loading; no save available.*

**Last log**: *
[message (2).txt](https://github.com/MEEPofFaith/prog-mats-java/files/11839509/message.2.txt)*

(This is a culled log, since this server is private and this is all that is needed.)

**Crash logs**: *See the above message.txt file*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
- [X] **I am playing with the latest release (https://github.com/MEEPofFaith/prog-mats-java/releases) to make sure my issue has not been fixed.**

**Comment by Austin5003** [comment]
🍞

**Comment by MEEPofFaith** [comment]
No, don't close yet.

**Comment by other-erisfg** [comment]
The build you sent me on Discord had the same error. Trying latest Actions build right now...

EDIT: Latest Actions build fails too. @MEEPofFaith From now on, at least throw the mod on a server before every release to make sure it starts...

**Comment by MEEPofFaith** [comment]
> EDIT: Latest Actions build fails too. @MEEPofFaith From now on, at least throw the mod on a server before every release to make sure it starts...

1. I never made a release.
2. I have no idea how to make a server.

**Comment by other-erisfg** [comment]
> > EDIT: Latest Actions build fails too. @MEEPofFaith From now on, at least throw the mod on a server before every release to make sure it starts...
> 
> 1. I never made a release.
> 2. I have no idea how to make a server.

1. I meant when you **do** make a release?
2. https://github.com/Anuken/Mindustry/releases/download/v145.1/server-release.jar (put the mod in config/mods after running it with Java)
