### ISSUE TITLE
Overdrive Diffuser gone?

### ISSUE THREAD

**Issue by joel4848** [MEEPofFaith/prog-mats-java#42]
**Platform**: *Android*

**Build**: *145.1*

**Mod Version**: *Latest? No version number shown in game mod menu*

**Issue**: *I installed this mod months/years ago, updated it recently (maybe a month ago) and can't find the Overdrive Diffuser anywhere. It's pretty much my most-used block and I don't know if I'm just looking in the wrong place for it or what?*

Edit: the 'bug' label probably isn't right but I can't change it, sorry.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
  - [X] **I am playing with the latest release (https://github.com/MEEPofFaith/prog-mats-java/releases) to make sure my issue has not been fixed.**

**Comment by MEEPofFaith** [comment]
removed, was janky
besides, overdriving only things connected to power isn't exactly the best way to boost production considering conveyors and some machines don't connect to power.

**Comment by Austin5003** [comment]
:(

**Comment by joel4848** [comment]
> removed, was janky besides, overdriving only things connected to power isn't exactly the best way to boost production considering conveyors and some machines don't connect to power.

On the flip side, being able to overdrive _everything_ connected to power with one block, rather than having to build loads, was much neater.

Do you recall which version was the last one to have them in?

**Comment by MEEPofFaith** [comment]
don't remember
check the patch notes on the releases, one of them should state the removal of the diffuser
