### ISSUE TITLE
Game crashes when enemy base is destoryed

### ISSUE THREAD

**Issue by mblazike** [MEEPofFaith/prog-mats-java#43]
Platform: android 

**Build**: 145.1

**Mod Version**: 27.3

**Issue**: I first got the mod as I started playing, and it worked fine, until I tried to destroy an enemy core. Then the while game crashed. I could go through waves, capture tiles, destroy normal enemy buildings, but I couldn't destroy the enemy core without crashing. It also threw an error at me when I tried to save after I had partially damaged the core. And one more thing, I opened this issue in the main mindustry bug repository, and they said it was a mod issue.

**Steps to reproduce**: I was playing the map normally, was about to capture the base, and started firing rockets at the enemy core. As soon as the last rocket hit to destroy the core, the game froze then crashed. So I tried again. And again. And then again with different tactics. I tried with my troops, I tried with different turrets, I even tried with my own ship. None of it worked. So I decided to save the exact moment before it crashed, and it threw and error at me. 

**Save file**: 
[midustry save.zip](https://github.com/MEEPofFaith/prog-mats-java/files/12206199/midustry.save.zip)

**Last log**: [I] [GL] Version: GLES 3.2.0 / ARM / Mali-G68
[I] [GL] Max texture size: 16383
[I] [GL] Using OpenGL 2 context.
[I] [JAVA] Version: 0
[I] [ANDROID] API level: 33
[I] [RAM] Available: 256.0 MB
[I] [Mindustry] Version: 145.1
[I] Loaded mod 'prog-mats' in 39.47931ms
[I] Total time to load: 5981ms
[I] Fetching community servers at https://raw.githubusercontent.com/Anuken/Mindustry/master/servers_v7.json
[I] Fetched 50 community servers.
[I] [AndroidGraphics] [pause]
[I] [AndroidGraphics] [resume]
[I] [AndroidGraphics] [pause]

**Crash logs**: because I'm on phone I can't open the real file so I found the text sheets and they all 30 of them said one of these things: 
Mindustry has crashed. How unfortunate.
Version: release build 143.1
OS: Linux xnull (aarch64)
Android API level: 33
Java Version: 0
Runtime Available Memory: 256mb
Cores: 8
Mods: informatis:1.7, prog-mats:27.2

> NullPointer: 'Attempt to read from field 'float mindustry.world.consumers.ConsumePower.usage' on a null object reference in method 'void informatis.ui.windows.BarInfo.getInfo(mindustry.gen.Teamc)''
BarInfo.getInfo: 436
UnitWindow.lambda$new$0: 77
-$$Lambda$UnitWindow$QGiTxogp_YYQjaLjW_6tg6Awulk.run: 0
Events.lambda$run$2: 0
Events.$r8$lambda$r1ZaaGUtG03In-r__kf9lAmJrDc: 0
Events$$ExternalSyntheticLambda0.get: 40
Events.fire: 4
Logic.update: 1
ApplicationCore.update: 2
ClientLauncher.update: 17
AndroidGraphics.onDrawFrame: 22
GLSurfaceView$GLThread.guardedRun: 1593
GLSurfaceView$GLThread.run: 1287
Or they said

Mindustry has crashed. How unfortunate.
Version: release build 144.1
OS: Linux xnull (aarch64)
Android API level: 33
Java Version: 0
Runtime Available Memory: 256mb
Cores: 8
Mods: prog-mats:27.2

> Runtime: 'java.lang.RuntimeException: java.io.IOException: Error writing region "map".'
SaveIO.save: 5
Saves$SaveSlot.save: 2
Saves.saveSector: 6
Logic.sectorCapture: 11
Call.sectorCapture: 2
Logic.checkGameState: 13
Logic.update: 43
ApplicationCore.update: 2
ClientLauncher.update: 17
AndroidGraphics.onDrawFrame: 22
GLSurfaceView$GLThread.guardedRun: 1593
GLSurfaceView$GLThread.run: 1287
> Runtime: 'java.io.IOException: Error writing region "map".'
SaveIO.write: 12
SaveIO.write: 1
SaveIO.write: 2
SaveIO.save: 3
Saves$SaveSlot.save: 2
Saves.saveSector: 6
Logic.sectorCapture: 11
Call.sectorCapture: 2
Logic.checkGameState: 13
Logic.update: 43
ApplicationCore.update: 2
ClientLauncher.update: 17
AndroidGraphics.onDrawFrame: 22
GLSurfaceView$GLThread.guardedRun: 1593
GLSurfaceView$GLThread.run: 1287
> IO: 'Error writing region "map".'
SaveFileReader.region: 18
SaveVersion.write: 4
SaveVersion.write: 1
SaveIO.write: 8
SaveIO.write: 1
SaveIO.write: 2
SaveIO.save: 3
Saves$SaveSlot.save: 2
Saves.saveSector: 6
Logic.sectorCapture: 11
Call.sectorCapture: 2
Logic.checkGameState: 13
Logic.update: 43
ApplicationCore.update: 2
ClientLauncher.update: 17
AndroidGraphics.onDrawFrame: 22
GLSurfaceView$GLThread.guardedRun: 1593
GLSurfaceView$GLThread.run: 1287
> NullPointer: 'Attempt to read from field 'short mindustry.ctype.Content.id' on a null object reference in method 'void progressed.world.blocks.production.SmartDrill$SmartDrillBuild.write(arc.util.io.Writes)''
SmartDrill$SmartDrillBuild.write: 221
Building.writeAll: 2
SaveVersion.lambda$writeMap$5: 2
SaveVersion.$r8$lambda$U2vHOaXUwbSaP91ciJETqR3GMLQ: 0
SaveVersion$$ExternalSyntheticLambda3.accept: 18
SaveFileReader.writeChunk: 11
SaveVersion.writeMap: 20
MapIO$$ExternalSyntheticLambda0.accept: 18
SaveFileReader.writeChunk: 11
SaveFileReader.writeChunk: 1
SaveFileReader.region: 15
SaveVersion.write: 4
SaveVersion.write: 1
SaveIO.write: 8
SaveIO.write: 1
SaveIO.write: 2
SaveIO.save: 3
Saves$SaveSlot.save: 2
Saves.saveSector: 6
Logic.sectorCapture: 11
Call.sectorCapture: 2
Logic.checkGameState: 13
Logic.update: 43
ApplicationCore.update: 2
ClientLauncher.update: 17
AndroidGraphics.onDrawFrame: 22
GLSurfaceView$GLThread.guardedRun: 1593
GLSurfaceView$GLThread.run: 1287

(The second one was the actual bug itself I'm not sure what the first was)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
  - [X] **I am playing with the latest release (https://github.com/MEEPofFaith/prog-mats-java/releases) to make sure my issue has not been fixed.**
   
    or
  - [X] **I am playing with the latest action (https://github.com/MEEPofFaith/prog-mats-java/actions) to make sure my issue has not been fixed.**

---

The original template is by Anuke, modified by sk7725, modified by MEEPofFaith.

**Comment by mblazike** [comment]
Btw I tried destroying the enemy core without the mod and it worked fine but I don't want to not use the mod because if I uninstall it it'll basically break my whole game because of all the molded items dissapearing

**Comment by MEEPofFaith** [comment]
The first crash report seems to be an issue with Informatis.

The second one is an issue with my mod, so I'm taking a look.

**Comment by mblazike** [comment]
Have you figured it out yet? It doesn't seem to be fixed on my end, sorry to bother you @MEEPofFaith

**Comment by MEEPofFaith** [comment]
As stated before, the first crash is caused by Informatis, and the second crash is caused by smart drills, which I've fixed.
