### ISSUE TITLE
where is the onmea item source 

### ISSUE THREAD

**Issue by Labbit35** [MEEPofFaith/prog-mats-java#45]
it's gone 

also not a bug idk how to change label

**Comment by MEEPofFaith** [comment]
See [patch notes](https://github.com/MEEPofFaith/prog-mats-java/releases/tag/v28.0). Moved to [Extra Sand Redux](https://github.com/MEEPofFaith/extra-sand-redux).

**Comment by MEEPofFaith** [comment]
I just realized I forgot to add the `mindustry-mod` tag to ESR.
