### ISSUE TITLE
droppod replacement concept, a debuff nuke

### ISSUE THREAD

**Issue by USMP-lancer** [MEEPofFaith/prog-mats-java#5]
does little damage, but applies a debuff, kinda like emp but it further nerfs the units, less towards movement and more towards nerfing their damage

**Comment by USMP-lancer** [comment]
dont expect a response anytime soon from now my device boutta die

**Comment by MEEPofFaith** [comment]
~~Mass status effect application doesn't sound original enough.~~

**Comment by USMP-lancer** [comment]
yea

**Comment by USMP-lancer** [comment]
fire nuke however, sounds fun, could just set everything on fire

**Comment by MEEPofFaith** [comment]
~~Have you seen how much fire that can be created with the eruptors~~

**Comment by USMP-lancer** [comment]
~~m o r e~~
