### ISSUE TITLE
[V7] downpour, barrage, and rapier unselectable in payload source

### ISSUE THREAD

**Issue by USMP-lancer** [MEEPofFaith/prog-mats-java#7]
ae

**Comment by MEEPofFaith** [comment]
this is an issue with all modded units, I don't know how to fix this

**Comment by LixieWulf** [comment]
Not all modded units - JSON mods are fine. Though you should make a bug report about it.

**Comment by Sh1penfire** [comment]
as far as I've seen it's a problem specific to units which extend UnitEntity
